### ISSUE TITLE
GRAYLOG_IS_MASTER Env variable not working

### ISSUE THREAD

**Issue by sppwf** [Graylog2/graylog-docker#14]
Hi,

Tring to set is_master = false for new slave node useing ENV - GRAYLOG_IS_MASTER, however graylog config still have "is_master = true" value.
Not sure why this variable does not work.
I am using latest tag for graylog docker container:
piece of yaml file for kubernetes:

```
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: graylog-slave
spec:
  serviceName: "graylog-slave"
  replicas: 1
  template:
    metadata:
      labels:
        role: graylog-slave
        graylog: "true"
    spec:
      containers:
        - name: graylog-slave
          image: graylog/graylog:latest
          env:
          - name: GRAYLOG_IS_MASTER
            value: "FALSE"
```
Thanks

**Comment by joschi** [comment]
> Tring to set is_master = false for new slave node useing ENV - GRAYLOG_IS_MASTER, however graylog config still have "is_master = true" value.

How exactly are you checking this?

**Comment by joschi** [comment]
I'm unable to reproduce this with Graylog 2.4.3.

I've been using the following `docker-compose.yml` file:
```
version: '2'
services:
  mongo:
    image: mongo:3
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.6
    environment:
      - http.host=0.0.0.0
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:2.4.3-1
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
      - GRAYLOG_IS_MASTER=false
    links:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
```

This is the node information directly from the Graylog REST API:
```
$ curl -u admin:admin 'http://127.0.0.1:9000/api/system/cluster/node?pretty=true'
{
  "cluster_id" : "00000000-0000-0000-0000-000000000000",
  "node_id" : "6001cd88-9250-41c7-8437-cefd4b6a78d5",
  "type" : "server",
  "transport_address" : "http://172.19.0.4:9000/api/",
  "last_seen" : "2018-01-30T12:45:19.000Z",
  "short_node_id" : "6001cd88",
  "hostname" : "20e868c9a8cf",
  "is_master" : false
}
```

`is_master: false` means that this node is *not* a master node.
