### ISSUE TITLE
GRAYLOG_MESSAGE_JOURNAL_MAX_SIZE ENV variable seems not to be applied

### ISSUE THREAD

**Issue by phlegx** [Graylog2/graylog-docker#17]
Hi,

I have set the ENV variable GRAYLOG_MESSAGE_JOURNAL_MAX_SIZE to 5Gb but the journal grows a whole lot bigger than that. Last time it was on 24 GB, due to another issue where Graylog cannot read messages anymore. 

Any ideas what might be wrong? Also if someone has a hint on what might causes Graylog to suddenly stop reading messages would be very helpful, since I run into this already several times.

I'm using latest docker image ```graylog2/server:2.4.3-1```

thanks

**Comment by joschi** [comment]
@phlegx Please post the complete configuration of your Graylog Docker container.

**Comment by phlegx** [comment]
```  
graylog:
    image: graylog2/server:2.4.3-1
    environment:
      TZ: Europe/Vienna
      GRAYLOG_PASSWORD_SECRET: pepper-xxxx
      GRAYLOG_ROOT_PASSWORD_SHA2: xxxxxxxx
      GRAYLOG_ROOT_TIMEZONE: Europe/Vienna
      GRAYLOG_TRANSPORT_EMAIL_ENABLED: 'true'
      GRAYLOG_TRANSPORT_EMAIL_HOSTNAME: mail.example.com
      GRAYLOG_TRANSPORT_EMAIL_PORT: '587'
      GRAYLOG_TRANSPORT_EMAIL_USE_AUTH: 'true'
      GRAYLOG_TRANSPORT_EMAIL_USE_TLS: 'true'
      GRAYLOG_TRANSPORT_EMAIL_USE_SSL: 'false'
      GRAYLOG_TRANSPORT_EMAIL_AUTH_USERNAME: admin@example.com
      GRAYLOG_TRANSPORT_EMAIL_AUTH_PASSWORD: xxxxxx
      GRAYLOG_TRANSPORT_EMAIL_SUBJECT_PREFIX: '[graylog]'
      GRAYLOG_TRANSPORT_EMAIL_FROM_EMAIL: graylog@example.com
      GRAYLOG_TRANSPORT_EMAIL_WEB_INTERFACE_URL: https://graylog.example.com
      GRAYLOG_REST_TRANSPORT_URI: https://graylog.example.com/api
      GRAYLOG_ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      GRAYLOG_MESSAGE_JOURNAL_MAX_SIZE: 5gb
    stdin_open: true
    volumes:
    - /root/.docker_data/graylog/graylog/data/journal:/usr/share/graylog/data/journal
    - /root/.docker_data/graylog/graylog/data/config:/usr/share/graylog/data/config
    tty: true
    ports:
    - 10.1.0.10:5514:5514/udp
    - 10.1.0.10:12201:12201/udp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: graylog.graylog=true
```
