### ISSUE TITLE
Graylog stuck at accepted stage with the new arm64 image 

### ISSUE THREAD

**Issue by kunalschrewd** [Graylog2/graylog-docker#179]
I have created a compose file for a stack (currently for single node).
```
version: "3.9"
services:

       mongodb:
          image: mongo:latest
          volumes:
            - mongo_data:/data/db
          environment:
            - MONGO_INITDB_ROOT_USERNAME=*********
            - MONGO_INITDB_ROOT_PASSWORD=*********
            - MONGO_INITDB_DATABASE=graylog.logs
          ports:
            - "27017:27017"
          deploy:
           replicas: 1
           restart_policy:
                condition: on-failure
          networks:
            - graylog
       elasticsearch:
image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
          environment:
            - http.host=0.0.0.0
            - transport.host=localhost
            - network.host=0.0.0.0
            - "ES_JAVA_OPTS=-Xms64m -Xmx64m"
          volumes:
            - es_data:/usr/share/elasticsearch/data
          ulimits:
           nofile:
                soft: 65536
                hard: 65536
          deploy:
           replicas: 1
           restart_policy:
                condition: on-failure
          ports:
            - "9200:9200"
          networks:
            - graylog
graylog:
          image: graylog/graylog:4.1-arm64
          volumes:
            - graylog_data:/usr/share/graylog/data
            - /etc/graylog/server:/etc/graylog/server
          environment:
            - GRAYLOG_PASSWORD_SECRET=****************
            - GRAYLOG_ROOT_PASSWORD_SHA2=**********
            - GRAYLOG_ROOT_USERNAME=*********
            - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
            - GRAYLOG_MONGODB_URI=mongodb+srv://*******:*******@cluster0.ffzty.mongodb.net/test
            - GRAYLOG_MONGODB_MAX_CONNECTIONS=1000
            - GRAYLOG_ELASTICSEARCH_VERSION=7
          entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
          ports:
           # Graylog web interface and REST API
            - 9000:9000
           # Syslog TCP
            - 1514:1514
           # Syslog UDP
            - 1514:1514/udp
           # GELF TCP
            - 12201:12201
           # GELF UDP
            - 12201:12201/udp
          networks:
            - graylog
networks:
  graylog:
volumes:
  mongo_data:
    driver: local
  es_data:
    driver: local
  graylog_data:
    driver: local
```
After deploying the stack the graylog service is stuck at accepted state. Tried a lot of work around but nothing seems to work. Nothing appears in logs too.Can you please look into it
![Screenshot from 2021-09-12 17-17-58](https://user-images.githubusercontent.com/84197671/132993235-8def9106-d9e8-44c3-8e07-16d2324ba206.png)
