### ISSUE TITLE
Graylog fails to run after updating docker image from 4.3.3 to 4.3.4

### ISSUE THREAD

**Issue by MahdiGhiasi** [Graylog2/graylog-docker#217]
We've updated our Graylog docker image to latest version pushed on `graylog/graylog:4.3` (which is 4.3.4), and since then the graylog container fails to start.

Inspecting docker logs shows that this seems to be the issue:

```
graylog_1        | adding environment opts
graylog_1        | mkdir: cannot create directory ‘/data’: Permission denied
```

Our elastic and mongo are running fine, but graylog container fails to start with the error message above.

We have two separate instances of Graylog (not linked, used separately by separate teams), and both have encountered this issue after upgrading. They were both working fine on v4.3.3.

---

We use a folder-mounted journal folder in our docker-compose file:

```
 graylog:
    image: graylog/graylog:4.3
    restart: always
    volumes:
      - /root/docker-data/graylog/graylog_journal:/usr/share/graylog/data/journal
```
