### ISSUE TITLE
Prometheus config file a bit misleading

### ISSUE THREAD

**Issue by suntereo** [Graylog2/graylog-docker#219]
The [grayling.conf](https://github.com/Graylog2/graylog-docker/blob/723d0ef3d28ce149238044671686e2239453456e/config/graylog.conf#L708-L730) file for this repo seems to suggest that Prometheus is automatically included. However, Prometheus is not automatically installed in the Docker version. You can see this by comparing [the Docker version](https://github.com/Graylog2/graylog-docker/search?q=prometheus) with [the non-Docker version](https://github.com/Graylog2/graylog2-server/search?q=prometheus).

This led to hours of confusion on my end. Poor me, I know. I would like to document what I did to get Prometheus working inside the Docker build. And maybe somebody can remove the Prometheus settings from the [grayling.conf](https://github.com/Graylog2/graylog-docker/blob/723d0ef3d28ce149238044671686e2239453456e/config/graylog.conf#L708-L730) file. Or better, bring Prometheus into this build as well.

**Here's how I installed the Prometheus Exporter for the Docker version**

1. Created a folder called GraylogPluginFolder on my local Mac.
2. Copied metrics-reporter-prometheus-3.0.0.jar from [here](https://github.com/graylog-labs/graylog-plugin-metrics-reporter/releases) into this folder. 
![image](https://user-images.githubusercontent.com/171720/186535527-62dad91a-5fb7-49ef-9f0c-3dd992cd067e.png)
3. Modified Docker Compose file to read from the plugins folder:
```
graylog:
    image: graylog/graylog:4.2
    volumes:
      - /Users/shawn/GrayLog/GraylogPluginFolder:/usr/share/graylog/plugin # <-- **THIS**
    environment:
      - GRAYLOG_PASSWORD_SECRET=hfghsfgjfgjfhjghkj
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=2378654782568726513459314
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      # don't try below; does not apply to Docker version because Prometheus is not automatically included
      # - prometheus_exporter_enabled=true
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      - 9000:9000 # Graylog web interface and REST API
      - 9090:9090
      - 5555:5555 # Raw/Plaintext TCP
      - 1514:1514 # Syslog TCP
      - 1514:1514/udp # Syslog UDP
      - 12201:12201 # GELF TCP
      - 12201:12201/udp # GELF UDP
```
4. Restarted Docker image and could now see in the startup logs:
```
2022-08-24 22:03:02,476 INFO : org.graylog2.bootstrap.CmdLineTool - Loaded plugin: Internal Metrics Prometheus Reporter 3.0.0 [org.graylog.plugins.metrics.prometheus.MetricsPrometheusReporterMetaData]
```
5. Went to this URL once Graylog was running:
[http://localhost:9000/api/plugins/org.graylog.plugins.metrics.prometheus/metrics](https://github.com/Graylog2/graylog-docker/issues/%22)

![image](https://user-images.githubusercontent.com/171720/186536100-0da2cf24-24e4-42e5-a0c8-859ce93dae11.png)

Hopefully that will help some struggling soul who is pulling their hair out over this!
