### ISSUE TITLE
graylog.conf is not updated from env variables

### ISSUE THREAD

**Issue by mpibpc-mroose** [Graylog2/graylog-docker#242]
I have added configuration to enable email in graylog to my `docker-compose.yml`:

```
graylog:
    hostname: "server"
    image: "${GRAYLOG_IMAGE:-graylog/graylog-enterprise:5.0}"
    depends_on:
      opensearch:
        condition: "service_started"
      mongodb:
        condition: "service_started"
    entrypoint: "/usr/bin/tini -- wait-for-it opensearch:9200 --  /docker-entrypoint.sh"
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/config/node-id"
      GRAYLOG_PASSWORD_SECRET: "${GRAYLOG_PASSWORD_SECRET:?Please configure GRAYLOG_PASSWORD_SECRET in the .env file}"
      GRAYLOG_ROOT_PASSWORD_SHA2: "${GRAYLOG_ROOT_PASSWORD_SHA2:?Please configure GRAYLOG_ROOT_PASSWORD_SHA2 in the .env file}"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9000/"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://opensearch:9200"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
      # To make reporting (headless_shell) work inside a Docker container
      GRAYLOG_REPORT_DISABLE_SANDBOX: "true"
      # email
      GRAYLOG_TRANSPORT_EMAIL_ENABLED: "false"
      GRAYLOG_TRANSPORT_EMAIL_HOSTNAME: "mail.example.com"
      GRAYLOG_TRANSPORT_EMAIL_PORT: "587"
      GRAYLOG_TRANSPORT_EMAIL_USE_AUTH: "true"
      GRAYLOG_TRANSPORT_EMAIL_USE_TLS: "true"
      GRAYLOG_TRANSPORT_EMAIL_USE_SSL: "false"
  
```
When I go into my running graylog container and grep for those the config options are not added/changed:

```
graylog@server:~/data/config$ set | grep TRANSPORT_EMAIL
GRAYLOG_TRANSPORT_EMAIL_ENABLED=false
GRAYLOG_TRANSPORT_EMAIL_HOSTNAME=mail.example.com
GRAYLOG_TRANSPORT_EMAIL_PORT=587
GRAYLOG_TRANSPORT_EMAIL_USE_AUTH=true
GRAYLOG_TRANSPORT_EMAIL_USE_SSL=false
GRAYLOG_TRANSPORT_EMAIL_USE_TLS=true
graylog@server:~/data/config$ grep transport_email graylog.conf
#transport_email_enabled = false
#transport_email_hostname = mail.example.com
#transport_email_port = 587
#transport_email_use_auth = true
#transport_email_auth_username = you@example.com
#transport_email_auth_password = secret
#transport_email_subject_prefix = [graylog]
#transport_email_from_email = graylog@example.com
#transport_email_use_tls = true
#transport_email_use_ssl = false
#transport_email_web_interface_url = https://graylog.example.com
```
I checked the `docker-entrypoint.sh` to find out, where the env variables get converted to the config file. But I was not able to find the code for that ...
